name: managerapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dbcrypt: ^2.0.0
  dio: ^5.4.1
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_cors: ^1.5.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^4.0.3
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - img/
